output:
  format: line-number
  print-issued-lines: false
  sort-results: true
linters:
  presets:
    - bugs
    - comment
    - complexity
    - format
    - import
    - metalinter
    - module
    - performance
    - unused
  disable:
    - gosec
    - cyclop
    - noctx
