output:
  format: line-number
  print-issued-lines: false
  sort-results: true
linters:
  enable-all: true
  disable:
    - ifshort
    - structcheck
    - maligned
    - exhaustivestruct
    - golint
    - interfacer
    - varcheck
    - nosnakecase
    - scopelint
    - deadcode
    - forbidigo
    - rowserrcheck
    - wastedassign
    - goerr113

    # We use globals to keep our code somewhat clean.
    - gochecknoglobals
    # TODO: i guess wrap or handle with fancy errors?
    - wrapcheck
    # Schizophrenic linter, complains about 'magic numbers'
    #   if len(os.Args) > 2
    - gomnd
    # Basically this will change the global permissions of files
    # from something along the lines of 0755 to 0o755, which does
    # not make sense when working with permissions.
    - gofumpt
    # Splitting functions is unrealistic in the context of the
    # functions that have just some lines above the limit
    # main()(16>10)
    - cyclop
    # Useless
    - noctx
issues:
  exclude-rules:

    # The struct variables are set after the declaration, since we re-use values
    # from the struct itself, to set values in the struct as well, which isnt
    # possible during declaration.
    - path: dirs.go
      linters:
        - exhaustruct

    # Better this way.
    - path: fflags.go
      linters:
        - funlen

    # Roblox uses MD5, we do not have a choice.
    - path: package.go
      linters:
        - gosec

    # False alarm.
    - linters:
        - errorlint
      source: "err == io.EOF"


    # Schizophrenic linter
    # G107: Potential HTTP request made with variable url
    # G110: Potential DoS vulnerability via decompression bomb
    - linters: gosec
      text: "G107:"
    - linters: gosec
      text: "G110:"
    # I trust Roblox with my Filesystem.
    - linters: gosec
      text: "G305:"
