name: Build
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v3
    - name: 'Setup Go'
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'
    - name: 'Make the vendor directory'
      run: go mod vendor
    - name: 'Package the vendor directory'
      run: XZ_OPT=-9 tar -Jc vendor -f vendor.tar.xz
    - name: Publish the vendor directory
      uses: actions/upload-artifact@v3
      with:
        name: go-vendor
        path: ./vendor.tar.xz
    - name: 'Build Vinegar'
      run: make
