name: Linter
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Setup Go'
        uses: actions/setup-go@v3
      - name: 'Run Linter'
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
